# Generated by Django 5.0.3 on 2024-03-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_product_specifications_remove_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deal',
            field=models.BooleanField(default=False),
        ),
    ]
